# Generated by Django 3.2.12 on 2022-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Last_Name'),
        ),
    ]
